name: FederatedReserve
favicon: null
layout_spectrum: 1
typography_spectrum: 0.29443
title: 'Who put Crypto in my Currency '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#0095d9'
    - '#656263'
    - '#cbcaca'
  brandStrength: 0.9666447939816862
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
