name: FederatedReserve
favicon: null
layout_spectrum: 1
typography_spectrum: 0.29443
title: 'Who put Crypto in my Currency '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f58220'
    - '#008cd2'
    - '#ed028c'
    - '#540a00'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
